### ISSUE TITLE
Sherlock can't run

### ISSUE THREAD

**Issue by midesuperbest1** [sherlock-project/sherlock#1102]
python3 sherlock
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shobzy/sherlock/sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "/home/shobzy/sherlock/sherlock/sherlock.py", line 18, in <module>
    import requests
  File "/home/shobzy/sherlock/sherlock/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/shobzy/sherlock/sherlock/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/home/shobzy/sherlock/sherlock/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "/home/shobzy/sherlock/sherlock/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
  File "/home/shobzy/sherlock/sherlock/urllib3/packages/ssl_match_hostname/__init__.py", line 11, in <module>
    from ssl import CertificateError, match_hostname
  File "/home/shobzy/sherlock/sherlock/ssl/__init__.py", line 140
    except SSLError, x:
                   ^
SyntaxError: invalid syntax

**Comment by Oakchris1955** [comment]
Did you run
`python3 -m pip install -r requirements.txt`
before running sherlock?

**Comment by sdushantha** [comment]
This is an issue with your environment and not Sherlock.

**Comment by midesuperbest1** [comment]
Yes, I ran
python3 -m pip install -r requirements.txt

**Comment by liliang8858** [comment]
```
E:\sherlock>python3 -m pip install -r requirements.txt
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python38\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python38\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
ValueError: source code string cannot contain null bytes
```
Why?
