### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Despiix** [sherlock-project/sherlock#1695]
- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [x ] I've verified that I'm running the latest version of Sherlock
- [x ] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

I am using a Kali linux machine. I am getting this error everytime i try to run this code.
ModuleNotFoundError: No module named '_bz2'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sherlock/__main__.py", line 21, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 12, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/usr/local/lib/python3.7/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/usr/local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/usr/local/lib/python3.7/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by sdushantha** [comment]
This seems to be an issue with your enviornment and not Sherlock itself. Try this solution: https://stackoverflow.com/a/61464947
