### ISSUE TITLE
Pinterest.com fails in Canada due to redirect to Pinterest.ca

### ISSUE THREAD

**Issue by TTWNO** [sherlock-project/sherlock#179]
When I was attempting to run tests, I noticed I was having some trouble working with Pinterest. On investigation, it appears that I'm being redirected with a 302 (moved *temporarily*) response, giving false negatives. Information below:

This is my wget for Pinterest.
```
--2019-02-26 17:31:35--  https://www.pinterest.com/noonewouldeverusethis7
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.pinterest.com (www.pinterest.com)... 23.59.157.14
Connecting to www.pinterest.com (www.pinterest.com)|23.59.157.14|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.pinterest.ca/noonewouldeverusethis7 [following]
--2019-02-26 17:31:36--  https://www.pinterest.ca/noonewouldeverusethis7
Resolving www.pinterest.ca (www.pinterest.ca)... 23.59.157.14
Connecting to www.pinterest.ca (www.pinterest.ca)|23.59.157.14|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.pinterest.ca/noonewouldeverusethis7/ [following]
--2019-02-26 17:31:36--  https://www.pinterest.ca/noonewouldeverusethis7/
Connecting to www.pinterest.ca (www.pinterest.ca)|23.59.157.14|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.pinterest.ca/?show_error=true [following]
--2019-02-26 17:31:37--  https://www.pinterest.ca/?show_error=true
Reusing existing connection to www.pinterest.ca:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘noonewouldeverusethis7.1’

noonewouldeverusethis7.1           [ <=>                                              ]  81.47K  --.-KB/s    in 0.05s   

2019-02-26 17:31:37 (1.61 MB/s) - ‘noonewouldeverusethis7.1’ saved [83427]

```

These are the tests failing:

```
...
Stdout:
[*] Checking username jack on:
[+] Twitter: https://www.twitter.com/jack
[*] Checking username dfox on:
[+] devRant: https://devrant.com/users/dfox
[*] Checking username blue on:
[-] Pinterest: Not Found!
[*] Checking username kevin on:
[+] Instagram: https://www.instagram.com/kevin
[*] Checking username zuck on:
[+] Facebook: https://www.facebook.com/zuck
.....
Stdout:
[*] Checking username blue on:
[+] Canva: https://www.canva.com/blue
[+] CreativeMarket: https://creativemarket.com/blue
[+] EVE Online: https://evewho.com/pilot/blue/
[+] EyeEm: https://www.eyeem.com/u/blue
[+] ImageShack: https://imageshack.us/user/blue
[+] MeetMe: https://www.meetme.com/blue
[+] Pastebin: https://pastebin.com/u/blue
[-] Pinterest: Not Found!
[+] WordPress: https://blue.wordpress.com/
[+] Zhihu: https://www.zhihu.com/people/blue
[+] devRant: https://devrant.com/users/blue
[+] iMGSRC.RU: https://imgsrc.ru/main/user.php?user=blue
[*] Checking username jenny on:
[+] Carbonmade: https://jenny.carbonmade.com
[*] Checking username Matt-Riggsby on:
[+] Quora: https://www.quora.com/profile/Matt-Riggsby
[*] Checking username smith on:
[+] VK: https://vk.com/smith

Stdout:
[*] Checking username blue on:
[+] 9GAG: https://9gag.com/u/blue
[+] About.me: https://about.me/blue
[+] Academia.edu: https://independent.academia.edu/blue
[-] AngelList: Not Found!
[+] Aptoide: https://blue.en.aptoide.com/
[+] AskFM: https://ask.fm/blue
[+] BLIP.fm: https://blip.fm/blue
[+] Badoo: https://badoo.com/profile/blue
[+] Bandcamp: https://www.bandcamp.com/blue
[+] Behance: https://www.behance.net/blue
[+] BitBucket: https://bitbucket.org/blue/
[+] Blogger: https://blue.blogspot.com
[+] BuzzFeed: https://buzzfeed.com/blue
[+] Cloob: https://www.cloob.com/name/blue
[+] Codecademy: https://www.codecademy.com/blue
[+] Codementor: https://www.codementor.io/blue
[+] Codepen: https://codepen.io/blue
[+] ColourLovers: https://www.colourlovers.com/lover/blue
[+] Coroflot: https://www.coroflot.com/blue
[+] Crevado: https://blue.crevado.com
[+] Crunchyroll: https://www.crunchyroll.com/user/blue
[+] DEV Community: https://dev.to/blue
[+] DailyMotion: https://www.dailymotion.com/blue
[+] Designspiration: https://www.designspiration.net/blue/
[+] DeviantART: https://blue.deviantart.com
[+] Disqus: https://disqus.com/blue
[+] Facebook: https://www.facebook.com/blue
[+] Flickr: https://www.flickr.com/people/blue
[+] Giphy: https://giphy.com/blue
[+] GitHub: https://www.github.com/blue
[+] Gitee: https://gitee.com/blue
[+] GoodReads: https://www.goodreads.com/blue
[+] Gravatar: http://en.gravatar.com/blue
[+] HubPages: https://hubpages.com/@blue
[+] Imgur: https://imgur.com/user/blue
[+] Itch.io: https://blue.itch.io/
[+] KanoWorld: https://api.kano.me/progress/user/blue
[+] Keybase: https://keybase.io/blue
[+] Launchpad: https://launchpad.net/~blue
[+] LiveJournal: https://blue.livejournal.com
[+] Mastodon: https://mstdn.io/@blue
[+] Medium: https://medium.com/@blue
[+] MyAnimeList: https://myanimelist.net/profile/blue
[+] Newgrounds: https://blue.newgrounds.com
[+] Patreon: https://www.patreon.com/blue
[+] Photobucket: https://photobucket.com/user/blue/library
[+] Pixabay: https://pixabay.com/en/users/blue
[+] Slack: https://blue.slack.com
[+] SlideShare: https://slideshare.net/blue
[+] SoundCloud: https://soundcloud.com/blue
[+] SourceForge: https://sourceforge.net/u/blue
[+] Spotify: https://open.spotify.com/user/blue
[+] Star Citizen: https://robertsspaceindustries.com/citizens/blue
[+] StreamMe: https://www.stream.me/blue
[+] TradingView: https://www.tradingview.com/u/blue/
[+] Trakt: https://www.trakt.tv/users/blue
[+] Twitch: https://m.twitch.tv/blue
[+] VSCO: https://vsco.co/blue
[+] Vimeo: https://vimeo.com/blue
[+] YouPic: https://youpic.com/photographer/blue/
[+] last.fm: https://last.fm/user/blue
[*] Checking username jenny on:
[+] CashMe: https://cash.me/jenny
[+] Investing.com: https://www.investing.com/traders/jenny
[+] Issuu: https://issuu.com/jenny
[+] Jimdo: https://jenny.jimdosite.com
[+] Unsplash: https://unsplash.com/@jenny
[+] Venmo: https://venmo.com/jenny
[*] Checking username user on:
[+] Etsy: https://www.etsy.com/shop/user
[*] Checking username dens on:
[+] Foursquare: https://foursquare.com/dens
[*] Checking username davidbrin1 on:
[+] Google Plus: https://plus.google.com/+davidbrin1
[*] Checking username dansbecker on:
[+] Kaggle: https://www.kaggle.com/dansbecker
[*] Checking username plug-dj-rock on:
[+] Plug.DJ: https://plug.dj/@/plug-dj-rock
[*] Checking username hello on:
[+] Smashcast: https://www.smashcast.tv/api/media/live/hello
[*] Checking username radkabalcarova on:
[+] WebNode: https://radkabalcarova.webnode.cz/
[*] Checking username support on:
[+] Wix: https://support.wix.com

======================================================================
FAIL: test_detect_true (tests.all.SherlockDetectTests) [Checking Username 'blue' exists on Site 'Pinterest']
Test Username Existence Detection.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tait/Documents/sherlock-QC/tests/base.py", line 105, in username_check
    self.assertEqual(result['exists'], exist_result_desired)
AssertionError: 'no' != 'yes'
- no
+ yes


Stdout:
[*] Checking username jack on:
[+] Twitter: https://www.twitter.com/jack
[*] Checking username dfox on:
[+] devRant: https://devrant.com/users/dfox
[*] Checking username blue on:
[-] Pinterest: Not Found!
[*] Checking username kevin on:
[+] Instagram: https://www.instagram.com/kevin
[*] Checking username zuck on:
[+] Facebook: https://www.facebook.com/zuck

======================================================================
FAIL: test_coverage_true_via_response_url (tests.all.SherlockSiteCoverageTests) [Checking Username 'blue' exists on Site 'Pinterest']
Test Username Does Exist Site Coverage (Via Response URL).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tait/Documents/sherlock-QC/tests/base.py", line 105, in username_check
    self.assertEqual(result['exists'], exist_result_desired)
AssertionError: 'no' != 'yes'
- no
+ yes


Stdout:
[*] Checking username blue on:
[+] Canva: https://www.canva.com/blue
[+] CreativeMarket: https://creativemarket.com/blue
[+] EVE Online: https://evewho.com/pilot/blue/
[+] EyeEm: https://www.eyeem.com/u/blue
[+] ImageShack: https://imageshack.us/user/blue
[+] MeetMe: https://www.meetme.com/blue
[+] Pastebin: https://pastebin.com/u/blue
[-] Pinterest: Not Found!
[+] WordPress: https://blue.wordpress.com/
[+] Zhihu: https://www.zhihu.com/people/blue
[+] devRant: https://devrant.com/users/blue
[+] iMGSRC.RU: https://imgsrc.ru/main/user.php?user=blue
[*] Checking username jenny on:
[+] Carbonmade: https://jenny.carbonmade.com
[*] Checking username Matt-Riggsby on:
[+] Quora: https://www.quora.com/profile/Matt-Riggsby
[*] Checking username smith on:
[+] VK: https://vk.com/smith

======================================================================
FAIL: test_coverage_true_via_status (tests.all.SherlockSiteCoverageTests) [Checking Username 'blue' exists on Site 'AngelList']
Test Username Does Exist Site Coverage (Via HTTP Status).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tait/Documents/sherlock-QC/tests/base.py", line 105, in username_check
    self.assertEqual(result['exists'], exist_result_desired)
AssertionError: 'no' != 'yes'
- no
+ yes


Stdout:
[*] Checking username blue on:
[+] 9GAG: https://9gag.com/u/blue
[+] About.me: https://about.me/blue
[+] Academia.edu: https://independent.academia.edu/blue
[-] AngelList: Not Found!
[+] Aptoide: https://blue.en.aptoide.com/
[+] AskFM: https://ask.fm/blue
[+] BLIP.fm: https://blip.fm/blue
[+] Badoo: https://badoo.com/profile/blue
[+] Bandcamp: https://www.bandcamp.com/blue
[+] Behance: https://www.behance.net/blue
[+] BitBucket: https://bitbucket.org/blue/
[+] Blogger: https://blue.blogspot.com
[+] BuzzFeed: https://buzzfeed.com/blue
[+] Cloob: https://www.cloob.com/name/blue
[+] Codecademy: https://www.codecademy.com/blue
[+] Codementor: https://www.codementor.io/blue
[+] Codepen: https://codepen.io/blue
[+] ColourLovers: https://www.colourlovers.com/lover/blue
[+] Coroflot: https://www.coroflot.com/blue
[+] Crevado: https://blue.crevado.com
[+] Crunchyroll: https://www.crunchyroll.com/user/blue
[+] DEV Community: https://dev.to/blue
[+] DailyMotion: https://www.dailymotion.com/blue
[+] Designspiration: https://www.designspiration.net/blue/
[+] DeviantART: https://blue.deviantart.com
[+] Disqus: https://disqus.com/blue
[+] Facebook: https://www.facebook.com/blue
[+] Flickr: https://www.flickr.com/people/blue
[+] Giphy: https://giphy.com/blue
[+] GitHub: https://www.github.com/blue
[+] Gitee: https://gitee.com/blue
[+] GoodReads: https://www.goodreads.com/blue
[+] Gravatar: http://en.gravatar.com/blue
[+] HubPages: https://hubpages.com/@blue
[+] Imgur: https://imgur.com/user/blue
[+] Itch.io: https://blue.itch.io/
[+] KanoWorld: https://api.kano.me/progress/user/blue
[+] Keybase: https://keybase.io/blue
[+] Launchpad: https://launchpad.net/~blue
[+] LiveJournal: https://blue.livejournal.com
[+] Mastodon: https://mstdn.io/@blue
[+] Medium: https://medium.com/@blue
[+] MyAnimeList: https://myanimelist.net/profile/blue
[+] Newgrounds: https://blue.newgrounds.com
[+] Patreon: https://www.patreon.com/blue
[+] Photobucket: https://photobucket.com/user/blue/library
[+] Pixabay: https://pixabay.com/en/users/blue
[+] Slack: https://blue.slack.com
[+] SlideShare: https://slideshare.net/blue
[+] SoundCloud: https://soundcloud.com/blue
[+] SourceForge: https://sourceforge.net/u/blue
[+] Spotify: https://open.spotify.com/user/blue
[+] Star Citizen: https://robertsspaceindustries.com/citizens/blue
[+] StreamMe: https://www.stream.me/blue
[+] TradingView: https://www.tradingview.com/u/blue/
[+] Trakt: https://www.trakt.tv/users/blue
[+] Twitch: https://m.twitch.tv/blue
[+] VSCO: https://vsco.co/blue
[+] Vimeo: https://vimeo.com/blue
[+] YouPic: https://youpic.com/photographer/blue/
[+] last.fm: https://last.fm/user/blue
[*] Checking username jenny on:
[+] CashMe: https://cash.me/jenny
[+] Investing.com: https://www.investing.com/traders/jenny
[+] Issuu: https://issuu.com/jenny
[+] Jimdo: https://jenny.jimdosite.com
[+] Unsplash: https://unsplash.com/@jenny
[+] Venmo: https://venmo.com/jenny
[*] Checking username user on:
[+] Etsy: https://www.etsy.com/shop/user
[*] Checking username dens on:
[+] Foursquare: https://foursquare.com/dens
[*] Checking username davidbrin1 on:
[+] Google Plus: https://plus.google.com/+davidbrin1
[*] Checking username dansbecker on:
[+] Kaggle: https://www.kaggle.com/dansbecker
[*] Checking username plug-dj-rock on:
[+] Plug.DJ: https://plug.dj/@/plug-dj-rock
[*] Checking username hello on:
[+] Smashcast: https://www.smashcast.tv/api/media/live/hello
[*] Checking username radkabalcarova on:
[+] WebNode: https://radkabalcarova.webnode.cz/
[*] Checking username support on:
[+] Wix: https://support.wix.com

----------------------------------------------------------------------
Ran 11 tests in 39.457s

FAILED (failures=3)
```

AngelList also didn't work, but I'm going to assume it's unrelated :)

**Comment by sdushantha** [comment]
Pinterest has been removed due to the false postives
