### ISSUE TITLE
Please help: PermissionError [Errno 13]

### ISSUE THREAD

**Issue by valarietan** [sherlock-project/sherlock#1949]
Hi there, newbie here. Please, may I get your advice on how to resolve this? 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/valarietan/sherlock/sherlock/__main__.py", line 22, in <module>
    sherlock.main()
  File "/Users/valarietan/sherlock/sherlock/sherlock.py", line 697, in main
    with open(result_file, "w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied

Saw this reported in 2020 and tried what was provided in the comments. But not successful. 

Thank you.

**Comment by Pasanlaksitha** [comment]
In Microsoft Windows, disable controlled folder access. or add Python to the list of permitted programs in Microsoft Windows for controlled folder access. I believe that is your problem. try it

**Comment by Pasanlaksitha** [comment]
> I have the same error, but I'm running under Windows with Vmware and Kali. Controlled folder access is off.

what is your prompt and used arguments to Sherlock?

and also here are a few things you can check or try to resolve this issue:

**File/Directory Permissions:**

Make sure that the directory where the script is trying to create the file has the appropriate write permissions for the user running the script.

**Run as Administrator/Superuser:**

If you're on a Unix-like system (Linux ), try running the script with elevated privileges using sudo.

**Specify a Different Output Directory:**

If the current directory doesn't have the necessary write permissions, you can try specifying a different directory or providing a complete path where the script has permission to write.

**Comment by sugo512** [comment]
That did it. I installed with sudo, so the Sherlock dir I was in was root root.

Thanks

**Comment by matheusfelipeog** [comment]
Thank you, @Pasanlaksitha, for the helpful instructions to solve the problem.

Did the above instructions work for you as well, @valarietan?

**Comment by valarietan** [comment]
Hi @Pasanlaksitha 

Thank you for the advice. But I'm not able to follow the instructions as I'm on Macbook Air. I used sudo to install as well. 
Will appreciate if you can advise how to change the permission?

Thank you.

**Comment by matheusfelipeog** [comment]
@valarietan, can you show the permissions you currently have in the directory and files of the cloned sherlock project?

Navigate to the base directory of sherlock and the sherlock package directory and use this command in both directories:

```bash
ls -l
```

**Comment by roblogic** [comment]
I have the same permissions problem. Installed sherlock on Mac via Homebrew. Error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/sherlock", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/Cellar/sherlock/0.15.0/libexec/lib/python3.13/site-packages/sherlock_project/sherlock.py", line 850, in main
    with open(result_file, "w", encoding="utf-8") as file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: 'fuzzball.txt'
```

I have run  `chmod +w /usr/local/bin/` and `chmod +w /usr/local/Cellar/sherlock/0.15.0/libexec/lib/python3.13/site-packages/sherlock_project/` but still get the same error. 

Why not just write the txt file to `$HOME` or `~`? Seems like a basic oversight here somewhere.
