### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by rapable** [sherlock-project/sherlock#1971]
Hello, there has been problem on your osint tool or mine i dont really know, may you please help me.?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\^^^^^^\sherlock\sherlock\__main__.py", line 21, in <module>
    import sherlock
  File "C:\Users\^^^^^^\sherlock\sherlock\sherlock.py", line 20, in <module>
    import requests
  File "C:\Users\^^^^^^\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\^^^^^^\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\^^^^^^\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\^^^^^^\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

Thank you.,

**Comment by matheusfelipeog** [comment]
Hi @rapable, thanks for opening this issue.

I can't help you with just this information. What exactly did you execute to get to this message in the traceback?

**Comment by sdushantha** [comment]
Closing this issue as it is an issue with user's environment and not Sherlock
