### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by Rjscar83** [sherlock-project/sherlock#2238]
### Installation method

Other (indicate below)

### Description

Using Termux I do everything step by step end up in $sherlock/Sherlock. Can I get a step by step build for my termux environment please that I can copy and paste?

### Steps to reproduce

It's not a bug
I just keep getting different error messages and can never get to the social search at all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Hey @Rjscar83 

> I do everything step by step

Can you describe these steps? We don't know what guide or documentation you're using.

**Comment by Josemigue789** [comment]
alguien me explica como instalar Sherlock

**Comment by Rjscar83** [comment]
Welcome to Termux

Docs:       https://doc.termux.com
Community:  https://social.termux.com

Working with packages:
 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Report issues at https://bugs.termux.com
~ $ pkg install python
Get:1 https://termux.net stable InRelease [1086 B]
Get:2 https://termux.net stable/main aarch64 Packages [229 kB]
Fetched 230 kB in 1s (240 kB/s)
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Installing:
  python

Installing dependencies:
  clang                       libxml2
  gdbm                        lld
  glib                        llvm
  libandroid-posix-semaphore  make
  libbz2                      ncurses-ui-libs
  libcompiler-rt              ndk-sysroot
  libcrypt                    pkg-config
  libffi                      python-ensurepip-wheels
  libiconv                    python-pip
  libllvm                     zstd
  libsqlite

Summary:
  Upgrading: 0, Installing: 22, Removing: 0, Not Upgrading: 1
  Download size: 104 MB
  Space needed: 645 MB

Continue? [Y/n] y
Get:1 https://termux.net stable/main aarch64 libcompiler-rt aarch64 18.1.8 [3026 kB]
Get:2 https://termux.net stable/main aarch64 libffi aarch64 3.4.6-1 [30.8 kB]
Get:3 https://termux.net stable/main aarch64 libxml2 aarch64 2.13.3 [468 kB]
Get:4 https://termux.net stable/main aarch64 zstd aarch64 1.5.6 [337 kB]
Get:5 https://termux.net stable/main aarch64 libllvm aarch64 18.1.8 [26.3 MB]
Get:6 https://termux.net stable/main aarch64 lld aarch64 18.1.8 [2258 kB]
Get:7 https://termux.net stable/main aarch64 llvm aarch64 18.1.8 [19.0 MB]
Get:8 https://termux.net stable/main aarch64 libiconv aarch64 1.17-1 [557 kB]
Get:9 https://termux.net stable/main aarch64 ndk-sysroot aarch64 26d-2 [1635 kB]
Get:10 https://termux.net stable/main aarch64 clang aarch64 18.1.8 [33.1 MB]
Get:11 https://termux.net stable/main aarch64 gdbm aarch64 1.23 [143 kB]
Get:12 https://termux.net stable/main aarch64 glib aarch64 2.80.4 [1362 kB]
Get:13 https://termux.net stable/main aarch64 libandroid-posix-semaphore aarch64 0.1-3 [4072 B]
Get:14 https://termux.net stable/main aarch64 libbz2 aarch64 1.0.8-7 [26.3 kB]
Get:15 https://termux.net stable/main aarch64 libcrypt aarch64 0.2-5 [8880 B]
Get:16 https://termux.net stable/main aarch64 libsqlite aarch64 3.46.0 [614 kB]
Get:17 https://termux.net stable/main aarch64 make aarch64 4.4.1 [241 kB]
Get:18 https://termux.net stable/main aarch64 ncurses-ui-libs aarch64 6.5.20240519-6 [32.9 kB]
Get:19 https://termux.net stable/main aarch64 pkg-config aarch64 0.29.2-2 [32.7 kB]
Get:20 https://termux.net stable/main aarch64 python aarch64 3.11.9-2 [8963 kB]
Get:21 https://termux.net stable/main aarch64 python-ensurepip-wheels all 3.11.9-2 [3029 kB]
Get:22 https://termux.net stable/main aarch64 python-pip all 24.2 [3032 kB]
Fetched 104 MB in 21s (4873 kB/s)
Selecting previously unselected package libcompiler-rt.
(Reading database ... 5300 files and directories currently installed.)
Preparing to unpack .../00-libcompiler-rt_18.1.8_aarch64.deb ...
Unpacking libcompiler-rt (18.1.8) ...
Selecting previously unselected package libffi.
Preparing to unpack .../01-libffi_3.4.6-1_aarch64.deb ...
Unpacking libffi (3.4.6-1) ...
Selecting previously unselected package libxml2.
Preparing to unpack .../02-libxml2_2.13.3_aarch64.deb ...
Unpacking libxml2 (2.13.3) ...
Selecting previously unselected package zstd.
Preparing to unpack .../03-zstd_1.5.6_aarch64.deb ...
Unpacking zstd (1.5.6) ...
Selecting previously unselected package libllvm.
Preparing to unpack .../04-libllvm_18.1.8_aarch64.deb ...
Unpacking libllvm (18.1.8) ...
Selecting previously unselected package lld.
Preparing to unpack .../05-lld_18.1.8_aarch64.deb ...
Unpacking lld (18.1.8) ...
Selecting previously unselected package llvm.
Preparing to unpack .../06-llvm_18.1.8_aarch64.deb ...
Unpacking llvm (18.1.8) ...
Selecting previously unselected package libiconv.
Preparing to unpack .../07-libiconv_1.17-1_aarch64.deb ...
Unpacking libiconv (1.17-1) ...
Selecting previously unselected package ndk-sysroot.
Preparing to unpack .../08-ndk-sysroot_26d-2_aarch64.deb ...
Unpacking ndk-sysroot (26d-2) ...
Selecting previously unselected package clang.
Preparing to unpack .../09-clang_18.1.8_aarch64.deb ...
Unpacking clang (18.1.8) ...
Selecting previously unselected package gdbm.
Preparing to unpack .../10-gdbm_1.23_aarch64.deb ...
Unpacking gdbm (1.23) ...
Selecting previously unselected package glib.
Preparing to unpack .../11-glib_2.80.4_aarch64.deb ...
Unpacking glib (2.80.4) ...
Selecting previously unselected package libandroid-posix-semaphore.
Preparing to unpack .../12-libandroid-posix-semaphore_0.1-3_aarch64.deb ...
Unpacking libandroid-posix-semaphore (0.1-3) ...
Selecting previously unselected package libbz2.
Preparing to unpack .../13-libbz2_1.0.8-7_aarch64.deb ...
Unpacking libbz2 (1.0.8-7) ...
Selecting previously unselected package libcrypt.
Preparing to unpack .../14-libcrypt_0.2-5_aarch64.deb ...
Unpacking libcrypt (0.2-5) ...
Selecting previously unselected package libsqlite.
Preparing to unpack .../15-libsqlite_3.46.0_aarch64.deb ...
Unpacking libsqlite (3.46.0) ...
Selecting previously unselected package make.
Preparing to unpack .../16-make_4.4.1_aarch64.deb ...
Unpacking make (4.4.1) ...
Selecting previously unselected package ncurses-ui-libs.
Preparing to unpack .../17-ncurses-ui-libs_6.5.20240519-6_aarch64.deb ...
Unpacking ncurses-ui-libs (6.5.20240519-6) ...
Selecting previously unselected package pkg-config.
Preparing to unpack .../18-pkg-config_0.29.2-2_aarch64.deb ...
Unpacking pkg-config (0.29.2-2) ...
Selecting previously unselected package python.
Preparing to unpack .../19-python_3.11.9-2_aarch64.deb ...
Unpacking python (3.11.9-2) ...
Selecting previously unselected package python-ensurepip-wheels.
Preparing to unpack .../20-python-ensurepip-wheels_3.11.9-2_all.deb ...
Unpacking python-ensurepip-wheels (3.11.9-2) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../21-python-pip_24.2_all.deb ...
Unpacking python-pip (24.2) ...
Setting up gdbm (1.23) ...
Setting up libbz2 (1.0.8-7) ...
Setting up libandroid-posix-semaphore (0.1-3) ...
Setting up libsqlite (3.46.0) ...
Setting up libffi (3.4.6-1) ...
Setting up libcrypt (0.2-5) ...
Setting up ncurses-ui-libs (6.5.20240519-6) ...
Setting up make (4.4.1) ...
Setting up libcompiler-rt (18.1.8) ...
Setting up glib (2.80.4) ...
Setting up python (3.11.9-2) ...
Setting up libxml2 (2.13.3) ...
Setting up zstd (1.5.6) ...
Setting up libiconv (1.17-1) ...
Setting up python-ensurepip-wheels (3.11.9-2) ...
Setting up ndk-sysroot (26d-2) ...
Setting up pkg-config (0.29.2-2) ...
Setting up libllvm (18.1.8) ...
Setting up lld (18.1.8) ...
Setting up llvm (18.1.8) ...
Setting up clang (18.1.8) ...
Setting up python-pip (24.2) ...
pip setup...
Writing to /data/data/com.termux/files/usr/etc/pip.conf
~ $ pkg install git
git is already the newest version (2.46.0).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 1
~ $ apt upgrade --python
Error: Command line option --python is not understood in combination with the other options
~ $ apt upgrade && apt uodate
Upgrading:
  command-not-found

Summary:
  Upgrading: 1, Installing: 0, Removing: 0, Not Upgrading: 0
  Download size: 80.3 kB
  Space needed: 4096 B

Continue? [Y/n] y
Get:1 https://termux.net stable/main aarch64 command-not-found aarch64 2.4.0-36 [80.3 kB]
Fetched 80.3 kB in 0s (241 kB/s)
(Reading database ... 17158 files and directories currently installed.)
Preparing to unpack .../command-not-found_2.4.0-36_aarch64.deb ...
Unpacking command-not-found (2.4.0-36) over (2.4.0-35) ...
Setting up command-not-found (2.4.0-36) ...
Error: Invalid operation uodate
~ $ apt update
Hit:1 https://termux.net stable InRelease
All packages are up to date.
~ $ git clone https://github.com/sherlock-project/sherlock.git
cd sherlock
virtualenv .
source bin/activate
Cloning into 'sherlock'...
remote: Enumerating objects: 9181, done.
remote: Counting objects: 100% (2928/2928), done.
remote: Compressing objects: 100% (507/507), done.
remote: Total 9181 (delta 2583), reused 2632 (delta 2408), pack-reused 6253
Receiving objects: 100% (9181/9181), 17.27 MiB | 5.37 MiB/s, done.
Resolving deltas: 100% (5825/5825), done.
virtualenv: command not found
bash: bin/activate: No such file or directory
~/sherlock $ ls
Dockerfile  devel  pyproject.toml  sherlock          tests
LICENSE     docs   pytest.ini      sherlock_project  tox.ini
~/sherlock $ pipx install -e .
No command pipx found, did you mean:
 Command pip in package python-pip
~/sherlock $ pip install -e .
Obtaining file:///data/data/com.termux/files/home/sherlock
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting PySocks<2.0.0,>=1.7.0 (from sherlock-project==0)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting certifi>=2019.6.16 (from sherlock-project==0)
  Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting colorama<0.5.0,>=0.4.1 (from sherlock-project==0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting openpyxl<4.0.0,>=3.0.10 (from sherlock-project==0)
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pandas<3.0.0,>=1.0.0 (from sherlock-project==0)
  Downloading pandas-2.2.2.tar.gz (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      Collecting meson-python==0.13.1
        Downloading meson_python-0.13.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson==1.2.1
        Downloading meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
      Collecting wheel
        Downloading wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting Cython==3.0.5
        Downloading Cython-3.0.5-py2.py3-none-any.whl.metadata (3.2 kB)
      Collecting numpy>=2.0.0rc1
        Downloading numpy-2.0.1.tar.gz (18.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.9/18.9 MB 5.2 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install backend dependencies did not run successfully.
        │ exit code: 1
        ╰─> [67 lines of output]
            Collecting ninja>=1.8.2
              Downloading ninja-1.11.1.1.tar.gz (132 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting patchelf>=0.11.0
              Downloading patchelf-0.17.2.1.tar.gz (167 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Building wheels for collected packages: ninja, patchelf
              Building wheel for ninja (pyproject.toml): started
              Building wheel for ninja (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error

              × Building wheel for ninja (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [15 lines of output]
                  /data/data/com.termux/files/usr/tmp/pip-build-env-ui66rr05/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
                    warnings.warn("git archive did not support describe output")
                  /data/data/com.termux/files/usr/tmp/pip-build-env-ui66rr05/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
                    warnings.warn("unprocessed git archival found (no export subst applied)")
                  Traceback (most recent call last):
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-ui66rr05/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-ui66rr05/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-ui66rr05/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err

                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for ninja
              Building wheel for patchelf (pyproject.toml): started
              Building wheel for patchelf (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error

              × Building wheel for patchelf (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [11 lines of output]
                  Traceback (most recent call last):
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-80f5oqrn/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-80f5oqrn/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-80f5oqrn/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err

                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for patchelf
            Failed to build ninja patchelf
            ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ninja, patchelf)
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install backend dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~/sherlock $

**Comment by ppfeister** [comment]
You aren't using a supported install method. No need to clone the repository. Reference the linked guide and choose a method, most likely pip, and let me know how it goes

**Comment by Rjscar83** [comment]
~/sherlock $ pip install -e .
Obtaining file:///data/data/com.termux/files/home/sherlock
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting PySocks<2.0.0,>=1.7.0 (from sherlock-project==0)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting certifi>=2019.6.16 (from sherlock-project==0)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting colorama<0.5.0,>=0.4.1 (from sherlock-project==0)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting openpyxl<4.0.0,>=3.0.10 (from sherlock-project==0)
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pandas<3.0.0,>=1.0.0 (from sherlock-project==0)
  Using cached pandas-2.2.2.tar.gz (4.4 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      Collecting meson-python==0.13.1
        Using cached meson_python-0.13.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson==1.2.1
        Using cached meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
      Collecting wheel
        Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting Cython==3.0.5
        Using cached Cython-3.0.5-py2.py3-none-any.whl.metadata (3.2 kB)
      Collecting numpy>=2.0.0rc1
        Using cached numpy-2.0.1.tar.gz (18.9 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install backend dependencies did not run successfully.
        │ exit code: 1
        ╰─> [67 lines of output]
            Collecting patchelf>=0.11.0
              Using cached patchelf-0.17.2.1.tar.gz (167 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting ninja>=1.8.2
              Using cached ninja-1.11.1.1.tar.gz (132 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Building wheels for collected packages: patchelf, ninja
              Building wheel for patchelf (pyproject.toml): started
              Building wheel for patchelf (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error

              × Building wheel for patchelf (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [11 lines of output]
                  Traceback (most recent call last):
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-okb2mdgk/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-okb2mdgk/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-okb2mdgk/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err

                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for patchelf
              Building wheel for ninja (pyproject.toml): started
              Building wheel for ninja (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error

              × Building wheel for ninja (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [15 lines of output]
                  /data/data/com.termux/files/usr/tmp/pip-build-env-qakchtuu/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
                    warnings.warn("git archive did not support describe output")
                  /data/data/com.termux/files/usr/tmp/pip-build-env-qakchtuu/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
                    warnings.warn("unprocessed git archival found (no export subst applied)")
                  Traceback (most recent call last):
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-qakchtuu/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-qakchtuu/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-qakchtuu/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err

                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for ninja
            Failed to build patchelf ninja
            ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (patchelf, ninja)
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install backend dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~/sherlock $

**Comment by ppfeister** [comment]
`pip install sherlock-project`
