### ISSUE TITLE
Deprecate support for Python 3.8

### ISSUE THREAD

**Issue by ppfeister** [sherlock-project/sherlock#2266]
### Description

Some versions of pandas and numpy are incompatible, and the compatible versions of pandas is not compatible with Python versions below 3.9. Since Python 3.8 is reaching EOL in about a month anyways, support for this version should now be deprecated to allow for more ready dependency resolution and avoidance of this fatal error.

```
Traceback (most recent call last):
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/bin/sherlock", line 3, in <module>
    from sherlock_project.sherlock import main
  File "/home/[redacted]/Documents/sherlock/sherlock_project/sherlock.py", line 21, in <module>
    import pandas as pd
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by isados** [comment]
how long does it normally take to merge possible fixes?

**Comment by ppfeister** [comment]
@isados It's really just a matter of everyone being busy. Are you encountering this error yourself?
