### ISSUE TITLE
Failed with Error Code 1

### ISSUE THREAD

**Issue by ArtMason** [sherlock-project/sherlock#288]
Good Day

After I enter the required command I get the following error.
```bash
artmason@artmason-KyushoJitsuWorld:~/sherlock$ pip3 install -r requirements.txt
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1a/b7/34eec2fe5a49718944e215fde81288eec1fa04638aa3fb57c1c6cd0f98c3/beautifulsoup4-4.8.0-py3-none-any.whl
Collecting bs4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-54nyhfd1/bs4/
```

After which python3 sherlock.py -h gives me the following.
```
Traceback (most recent call last):
  File "sherlock.py", line 22, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama
```
Any help is appreciated!
Thank you!

**Comment by sdushantha** [comment]
@ArtMason 
You need to install `setuptools` and `colorama` like this:

**Comment by hoadlck** [comment]
This does appear to be a installation issue, so I am closing this now.
