### ISSUE TITLE
Install tor in the sistem path?

### ISSUE THREAD

**Issue by F3lixD** [sherlock-project/sherlock#291]
```
Traceback (most recent call last):
  File "sherlock.py", line 607, in <module>
    main()
  File "sherlock.py", line 571, in main
    tor=args.tor, unique_tor=args.unique_tor, proxy=args.proxy, print_found_only=args.print_found_only)
  File "sherlock.py", line 181, in sherlock
    underlying_request = TorRequest()
  File "/home/ubuntu-vb/.local/lib/python3.7/site-packages/torrequest.py", line 21, in __init__
    self._tor_proc = self._launch_tor()
  File "/home/ubuntu-vb/.local/lib/python3.7/site-packages/torrequest.py", line 46, in _launch_tor
    take_ownership=True)
  File "/home/ubuntu-vb/.local/lib/python3.7/site-packages/stem/process.py", line 285, in launch_tor_with_config
    return launch_tor(tor_cmd, ['-f', '-'], None, completion_percent, init_msg_handler, timeout, take_ownership, close_output, stdin = config_str)
  File "/home/ubuntu-vb/.local/lib/python3.7/site-packages/stem/process.py", line 158, in launch_tor
    raise OSError('Process terminated: %s' % last_problem)
OSError: Process terminated: Failed to bind one of the listener ports.
```
-------------------------------------

someone can explain how fix that?

**Comment by iocohen** [comment]
i have it also!

**Comment by iocohen** [comment]
I fiexed the issue by doing bash install_requirements.sh -->this fixed the issue. previously instaled it with python3 -r install requirements.txt Now is working
