### ISSUE TITLE
Recent updates broke sherlock

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#432]
Apparently an error somewhere in data.json.

```
Checking username cghgc on:
Traceback (most recent call last):
  File "sherlock.py", line 649, in <module>
    main()
  File "sherlock.py", line 613, in main
    timeout=args.timeout)
  File "sherlock.py", line 168, in sherlock
    executor = ThreadPoolExecutor(max_workers=len(site_data))
TypeError: object of type 'NoneType' has no len()
```

**Comment by torerobo** [comment]
Sorry, false alarm: wrong copy-paste passed from chrome android

**Comment by hoadlck** [comment]
Whew! I was going thru my e-mails after waking up in the morning, and saw this.  Glad everything is OK. :)
