### ISSUE TITLE
"Error: Command errored out with exit status 1:"

### ISSUE THREAD

**Issue by LewisTheKali** [sherlock-project/sherlock#606]
here is the full error message when installing  ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r8m7514n/bs4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r8m7514n/bs4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r8m7514n/bs4/pip-egg-info
         cwd: /tmp/pip-install-r8m7514n/bs4/
    Complete output (11 lines):                                            
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 15, in <module>                                                              
        from setuptools.extern.six import PY3, string_types                
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load    
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                      
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked    
      File "<frozen importlib._bootstrap_external>", line 779, in exec_module                                                                         
      File "<frozen importlib._bootstrap_external>", line 915, in get_code 
      File "<frozen importlib._bootstrap_external>", line 973, in get_data 
    OSError: [Errno 5] Input/output error                                  
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                      

how can i fix this??

**Comment by sdushantha** [comment]
@LewisTheKali Could you please provide which provide what command you ran whcih caused this error? Also, can you tell us what the output of this command?
```
python3 --version
```
