### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ZteamDL** [sherlock-project/sherlock#612]
root@kali:~/sherlock# python sherlock JustinBieber
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/sherlock/sherlock/__main__.py", line 10, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 381
    raise ValueError(f"Unknown Error Type '{error_type}' for "
                                                             ^
SyntaxError: invalid syntax

**Comment by sdushantha** [comment]
Hi @ZteamDL !

Looks like you are running Python2.7, but Sherlock only supports Python3.6 or above.
Try running Sherlock with `python3` instead of `python` and that should fix the problem you are having :)

**Comment by Dominatez** [comment]
user@cloudshell:~/cloudshell_open/sherlock$ python3 --version
Python 3.7.3
user@cloudshell:~/cloudshell_open/sherlock$ python3 sherlock --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
  File "sherlock/__main__.py", line 10, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 20, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

Definetely something not working here.

**Comment by sdushantha** [comment]
@Dominatez you are missing a module named `requests_future`. Please install all the needed dependencies for Sherlock to work properly
