### ISSUE TITLE
I got a DLL load failed when trying to use sherlock

### ISSUE THREAD

**Issue by mikewakawski** [sherlock-project/sherlock#794]
I got this error while trying to run sherlock

`Traceback (most recent call last):
  File "C:\Users\A\Documents\sherlock\sherlock\sherlock.py", line 21, in <module>
    from torrequest import TorRequest
  File "C:\Users\A\Anaconda3\lib\site-packages\torrequest.py", line 3, in <module>
    from stem.control import Controller
  File "C:\Users\A\Anaconda3\lib\site-packages\stem\control.py", line 271, in <module>
    import stem.descriptor.microdescriptor
  File "C:\Users\A\Anaconda3\lib\site-packages\stem\descriptor\__init__.py", line 1544, in <module>
    import stem.descriptor.hidden_service
  File "C:\Users\A\Anaconda3\lib\site-packages\stem\descriptor\hidden_service.py", line 44, in <module>
    import stem.client.datatype
  File "C:\Users\A\Anaconda3\lib\site-packages\stem\client\__init__.py", line 33, in <module>
    import stem.socket
  File "C:\Users\A\Anaconda3\lib\site-packages\stem\socket.py", line 77, in <module>
    import ssl
  File "C:\Users\A\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.`

**Comment by sdushantha** [comment]
@mikewakawski This is an error with your computer and not Sherlock. Please try Googleing you error or asking for help on Stackoverflow.
