### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by beesuns** [sherlock-project/sherlock#873]
I am using kali linux
```
kali@kali:~/Downloads/sherlock$ uname -a
Linux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux
```
After install all the requirements manually, I tried to run sherlock but there was a problem.
```
kali@kali:~/Downloads/sherlock$ python3 sherlock -help
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/Downloads/sherlock/sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "/home/kali/Downloads/sherlock/sherlock/sherlock.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
I tried to install module 'requests' and still not work.
```
kali@kali:~/Downloads/sherlock$ sudo apt-get install python3-requests
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-requests is already the newest version (2.24.0+dfsg-1).
python3-requests set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
How to solve this?

**Comment by sdushantha** [comment]
This is not an issue with Sherlock. It is an issue with your environment. 

I am closing this issue as invalid because you did not follow the issue template.
