### ISSUE TITLE
How to solve 'Failed to establish a new connection' problem

### ISSUE THREAD

**Issue by beesuns** [sherlock-project/sherlock#878]
I was using Kali Linux 
```
kali@kali:~/Downloads/sherlock$ uname -a
Linux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux
```
And I installed all the requirements
```
kali@kali:~/Downloads/sherlock$ python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4>=4.8.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: bs4>=0.0.1 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: certifi>=2019.6.16 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2020.11.8)
Requirement already satisfied: colorama>=0.4.1 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: lxml>=4.4.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.6.1)
Requirement already satisfied: PySocks>=1.7.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: requests>=2.22.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.25.0)
Requirement already satisfied: requests-futures>=1.0.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: soupsieve>=1.9.2 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.0.1)
Requirement already satisfied: stem>=1.8.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (1.8.0)
Requirement already satisfied: torrequest>=0.1.0 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (0.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/kali/.local/lib/python3.9/site-packages (from requests>=2.22.0->-r requirements.txt (line 7)) (1.26.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/kali/.local/lib/python3.9/site-packages (from requests>=2.22.0->-r requirements.txt (line 7)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/kali/.local/lib/python3.9/site-packages (from requests>=2.22.0->-r requirements.txt (line 7)) (2.10)
```
But when I run sherlock, there was a Failed to establish a new connection problem
```
kali@kali:~/Downloads/sherlock$ python3 sherlock username
A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f638a422c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f638a3d34c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
I tried to run with sudo 
```
kali@kali:~/Downloads/sherlock$ sudo python3 sherlock username
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/Downloads/sherlock/sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "/home/kali/Downloads/sherlock/sherlock/sherlock.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
How can I fix this?

**Comment by sdushantha** [comment]
I'm sorry, but I cannot help you with this problem because it has nothing to do with Sherlock. You also did not follow the template for the Question, therefore I'm closing this issue as invalid
