### ISSUE TITLE
sherlock.py isn't working please help me

### ISSUE THREAD

**Issue by xxbadboy17** [sherlock-project/sherlock#892]
**PLEASE HELP ME IT SHOWS AN ERROR**

**                                                                              
┌**──(babyboy17㉿kali)-[~/sherlock/sherlock]
└─$ python3 sherlock.py littlebitmore1   
Traceback (most recent call last):
  File "/home/babyboy17/sherlock/sherlock/sherlock.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'**
![Screenshot from 2020-12-13 **10-38-30](https://user-images.githubusercontent.com/75915365/101999359-3ac2b580-3d02-11eb-9f29-5acd8b66ffb5.png)**

**Comment by maatiug** [comment]
Run in console:
```
python3 -m pip install -r requirements.txt
```

Read README.md next time. ;)

**Comment by xxbadboy17** [comment]
I already did But its not run

**Comment by maatiug** [comment]
Can you try install modules one by one.. Firstly do:
```
pip3 install requests
```

And before update pip:
```
pip3 install update
```

**Comment by xxbadboy17** [comment]
Okay sir thanks

**Comment by maatiug** [comment]
Youre welcome. If it works, you can close this issue ;)

**Comment by teven70** [comment]
┌──(root㉿kali)-[/home/teven/sherlock/sherlock]
└─# ./sherlock.py   
Traceback (most recent call last):
  File "/home/teven/sherlock/sherlock/./sherlock.py", line 20, in <module>
    import requests
  File "/usr/local/lib/python3.11/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.11/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

thats what i get. help! sherlock wont run for me
