### ISSUE TITLE
Scan doesnt end

### ISSUE THREAD

**Issue by alexsmith2709** [sherlock-project/sherlock#990]
I am having trouble with sherlock because the scan doesnt end. It reaches the last website (or what i assume is the last one Zhizu) and then just sits there. I left it for several hours last night. The computer isnt frozen, i can do other things, but i have to press ctrl+C twice to end the program.
When pressing ctrl+C i get the following error:
```
Traceback (most recent call last):
  File "/usr/share/sherlock/sherlock.py", line 610, in <module>
    main()
  File "/usr/share/sherlock/sherlock.py", line 573, in main
    results = sherlock(username, site_data, verbose=args.verbose,
  File "/usr/share/sherlock/sherlock.py", line 287, in sherlock
    r, error_type, response_time = get_response(request_future=future,
  File "/usr/share/sherlock/sherlock.py", line 111, in get_response
    rsp = request_future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 435, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```
And then when pressing ctrl+C again i get this:
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1415, in _shutdown
    atexit_call()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt:
```
I am using Kali Linux 2021.1. I have both python 2.7.18 and python 3.9.1+ installed and i have run using both versions (i think) by running sherlock <username> and python3 /usr/share/sherlock/sherlock.py <username>

**Comment by buttpooper23** [comment]
ALEX SMITH YOU ARE LYING
